version: '3.7'

services:
  postgres:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${POSTGRES_DIR}:/var/lib/postgresql/data/pgdata
      - /etc/passwd:/etc/passwd:ro
    ports:
      - '${POSTGRES_PORT}:5432'
    restart: 'no'
    user: '${UID}:${GID}'
